### ISSUE TITLE
Model for numbers only

### ISSUE THREAD

**Issue by MahmoudMabrok** [AmrHendy/Arabic-Handwritten-Images-Recognition#3] opened 2020-07-20 05:57 UTC
Could u check code here, make sure it was  written correctly 

https://colab.research.google.com/drive/1Ng7jmPpHf-uJFqEuyHNpIDjtHEx9mo8T?usp=sharing

**Comment by AmrHendy** [comment] 2020-07-23 14:30
Please include more information about the issue and how to reproduce it in the description.
Also, specify the main issue or error in the released code not linking to other codes.

**Comment by MahmoudMabrok** [comment] 2020-07-23 18:13
I want a model for numbers only

link above is my edits for code, please check it

**Comment by AmrHendy** [comment] 2020-07-24 00:38
Unfortunately I don't have much time to check your version at the current time.
Since this issue has no related problems or bugs to the released code, I will close it and will update you If I have chance to check your code.

**Closed as completed by AmrHendy** 2020-07-24 00:38 UTC
